
- name: create /etc/systemd/system/docker.service.d/ dir
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d/
    owner: root
    group: root
    state: directory
    mode: '0775'

- name: Fix proxy for docker daemon
  ansible.builtin.template:
    src: docker-http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload docker