---

- name: Install repo manager package
  ansible.builtin.package:
    name: "{{ repo_manager_package_name[{{ ansible_distribution | lower }}] }}"
    state: present
    update_cache: yes

- ansible.builtin.command: "{{ repo_manager_cmd[{{ ansible_distribution | lower }}] }} --add-repo https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo"
